### ISSUE TITLE
Files view - need to manually refresh the page to display new uploaded files

### ISSUE THREAD

**Issue by Kurtil** [bimdata/platform#117]
![eee7419a7b1b57937bdbde57a565dc19](https://user-images.githubusercontent.com/22523482/151159781-2fd975d3-936b-47a1-abe3-eae7fe7e6542.gif)

Once uploaded, the new file does not appear in the list without manually refreshing the page.

**Comment by NicolasRichel** [comment]
I'm not able to reproduce this issue..

@Kurtil  Can you retry and wait about a second after you uploaded the file to see if the table is actually not being refreshed ?

Note: I intentionally introduced a debounce period between each refresh in order to prevent useless request when uploading multiple files at the same time.

**Comment by amineau** [comment]
It is probably due to a side effect of database replication.
The api creates the file on a database, and right after, the api gets the list of files on a second database before the synchronization between the db.

**Comment by NicolasRichel** [comment]
Thanks @amineau  :)
I wasn't aware of this possible cause of "bug".

Knowing that, my first try would be to add a small delay (say ~500ms or so) before triggering the refresh request in order to allow the databases to be synchronized.

Do you think this would be enough to avoid this kind of problem ?
Or, maybe, you think of another approach to mitigate this ?

**Comment by amineau** [comment]
Another approach to mitigate this problem is to send an api call with a cookie dropped by a previous write api call. This is in progress

**Comment by Amoki** [comment]
I'd rather revert [fe54ff9](https://github.com/bimdata/platform-next/commit/fe54ff9edf7ee5b59f1717d102d621bad960721a)
We really don't want to handle this client side
