### ISSUE TITLE
Escalade de privilèges - droits d'accès enfants GED

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform#225]
![Group 27197](https://user-images.githubusercontent.com/32667664/169258320-7a2ffe50-c5ac-4111-b286-58d95e8ab9a6.png)

On en avait discuté à l'époque mais désormais c'est nécessaire d'empêcher l'utilisateur de pouvoir mettre des droits supérieur au parents à un enfant de ce dernier (Antoine me dit dans l'oreillette que ça s'appelle l'escalade de privilèges). 

Notre solution serait de "griser" et de ne plus pas rendre cliquable dans le select le droit en question. (cf. image ci-dessus)

**Comment by NicolasRichel** [comment]
Solution envisagée: utilisation d'un **"droit par défaut"** au lieu de **"droit pour tout le monde"**.

**Comment by GabBimdata** [comment]
Ajouter "Par défaut" dans le select des "groupes".

**Comment by amineau** [comment]
C'est prêt côté back : https://github.com/bimdata/python-api/commit/ee1feb6dea0e33be2bb04c3270974bda04aed608

**Comment by NicolasRichel** [comment]
A new solution has been found to properly handle default folder perm and group perm propagation.
An explicit `propagate` field should be passed to the API in order to apply group perm recursively.
See related commit in python-api: https://github.com/bimdata/python-api/commit/4b14b907e66a1cac0746b4b11b2f99f8dd6c97fc
